### ISSUE TITLE
memchr 2.5.0 fails to compile on Android

### ISSUE THREAD

**Issue by Storyyeller** [BurntSushi/memchr#115]
After upgrading to 2.5.0, I'm getting build errors on Android like this:

```
[CONTEXT] stderr: error[E0531]: cannot find tuple struct or tuple variant `GenericSIMD128` in this scope
[CONTEXT]    --> third-party/rust/vendor/memchr-2.5.0/src/memmem/mod.rs:885:13
[CONTEXT]     |
[CONTEXT] 885 |             GenericSIMD128(gs) => GenericSIMD128(gs),
[CONTEXT]     |             ^^^^^^^^^^^^^^ not found in this scope
[CONTEXT] 
```

It appears that the GenericSIMD128 enum variant is defined with cfg target_arg = "x86_64" or memchr_runtime_wasm128, but then it is used in the code without a cfg check limiting it to those platforms, causing it to fail to compile.

**Comment by BurntSushi** [comment]
Your diagnosis looks right. Patches welcome, otherwise I'll fix this when I get to it. Bonus points for finding a way to put an Android build in CI. :)

**Comment by BurntSushi** [comment]
(One possibility is that there is a weird build environment that is not using build scripts or is using them improperly somehow. But without an actual reproduction, it's impossible to say.)
